config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.3.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      this_repo:
        commands:
        - git rev-parse --is-inside-work-tree
        container: qc.acc_muzzy-crimson-shark
  QC.Doc:
    repos:
      this_repo:
        commands:
        - git rev-parse --is-inside-work-tree
        container: qc.doc_snazzy-ivory-owl
      this_repo__2:
        commands:
        - rst-lint --level warning --format json . docs
        container: qc.doc_gummy-cyan-rattlesnake
  QC.Lic:
    repos:
      this_repo:
        commands:
        - licensee detect . --json
        container: qc.lic_woozy-ochre-gibbon
  QC.Sty:
    repos:
      this_repo:
        commands:
        - flake8 .
        container: qc.sty_blurry-saffron-earwig
timeout: 600
